FROM alpine:latest as builder

RUN    apk update \
    && apk add --no-cache  \
           alpine-sdk \
           coreutils \
           cmake \
    && adduser -G abuild -g "Alpine Package Builder" -s /bin/ash -D builder \
    && echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER builder
WORKDIR /home/builder
RUN abuild-keygen -ainq

ENTRYPOINT ["abuild","-r"]
